### ISSUE TITLE
on_delete argument error under Django 2.0.3

### ISSUE THREAD

**Issue by Vidder** [nnsnodnb/django-ios-storekit#11]
When running under Django 2.0.3, I get the following:

> in_app = models.ForeignKey(InApp, blank=True)
> TypeError: __init__() missing 1 required positional argument: 'on_delete'

Is Django 2.x not supported?

**Comment by nnsnodnb** [comment]
Sorry:cry:

`django-ios-storekit` doesn't support `Django2.x` yet.

**Comment by nnsnodnb** [comment]
@Vidder 
Hi, I released new version for `django-ios-storekit` .

```bash
$ pip install django-ios-storekit==1.0.2
# or 
$ pip install -U django-ios-storekit
```

**Comment by Vidder** [comment]
Thank you. I do not see the error any more.
